name: PULL REQUEST
  # You may pin to the exact commit or the version.
  # uses: peterjgrainger/action-create-branch@b48b0ca0e307c9b56f059b70274984ffeaa90a43
on:
  create:
    branches: 
      - releases/*

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "release/"
          PULL_REQUEST_BRANCH: "master"
    
